### ISSUE TITLE
ERROR: "NetworkError: 500 Internal Server Error - http://abcd.com/"

### ISSUE THREAD

**Issue by sh-sabbir** [halgatewood/Stripe-Donations-for-WordPress#2]
It's generating token successfully . But while tries to post the donation to stripe it show this error on console . Please fix this issue.

**Comment by halgatewood** [comment]
Are you on a test server?

**Comment by sh-sabbir** [comment]
Yes. I'm using a sub domain and with test mode.

**Comment by halgatewood** [comment]
My plugin posts to the value found from get_site_url(): https://codex.wordpress.org/Function_Reference/get_site_url

Make sure that is a real URL.

**Comment by sh-sabbir** [comment]
it's real...I added the live url .Please check.

**Comment by halgatewood** [comment]
Do you have cURL installed?

**Comment by sh-sabbir** [comment]
not checked.

**Comment by sh-sabbir** [comment]
Yes installed

**Comment by sh-sabbir** [comment]
Solved My problem. I was using the WordPress.org version of this plugin. Just downloaded and install this one. And changed a little thing .My problem is gone. Thanks for making such an awesome plugin.

**Comment by halgatewood** [comment]
Did you change a little thing that others would have to do too?

**Comment by sh-sabbir** [comment]
Yes...i pushed a piece of change to ajax-post.php
